import React, { useState, useEffect, useRef } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ActivityIndicator, Share, PermissionsAndroid, Platform } from 'react-native';
import QRCode from 'react-native-qrcode-svg';
import { CameraView } from 'expo-camera';
import Toast from 'react-native-toast-message';
import { router } from 'expo-router';
import { getApiClient, ComparisonSession } from '@bus/shared';
import { Colors, FontSize, Spacing, Radii, Fonts } from '../../src/constants/theme';

interface SessionStatus {
  id: string;
  token: string;
  expiresAt: string;
  used: boolean;
  comparisonId: string | null;
}

type Mode = 'show' | 'scan';

export default function CompareScreen() {
  const [mode, setMode] = useState<Mode>('show');

  // — Show mode state —
  const [session, setSession] = useState<ComparisonSession | null>(null);
  const [loading, setLoading] = useState(false);
  const [waiting, setWaiting] = useState(false);
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // — Scan mode state —
  const [cameraGranted, setCameraGranted] = useState<boolean | null>(null);
  const [scanned, setScanned] = useState(false);

  const stopPolling = () => {
    if (pollRef.current) { clearInterval(pollRef.current); pollRef.current = null; }
  };

  useEffect(() => () => stopPolling(), []);

  // Check / request camera permission whenever scan mode is opened
  useEffect(() => {
    if (mode !== 'scan') return;
    setScanned(false);
    (async () => {
      try {
        if (Platform.OS === 'android') {
          const result = await PermissionsAndroid.request(
            PermissionsAndroid.PERMISSIONS.CAMERA,
            { title: 'Camera Access', message: 'Between Us needs camera access to scan QR codes.', buttonPositive: 'Allow', buttonNegative: 'Deny' }
          );
          setCameraGranted(result === PermissionsAndroid.RESULTS.GRANTED);
        } else {
          const { getCameraPermissionsAsync, requestCameraPermissionsAsync } = await import('expo-camera');
          const { status } = await getCameraPermissionsAsync();
          if (status === 'granted') { setCameraGranted(true); return; }
          const { status: req } = await requestCameraPermissionsAsync();
          setCameraGranted(req === 'granted');
        }
      } catch {
        setCameraGranted(false);
      }
    })();
  }, [mode]);

  const startPolling = (sessionId: string) => {
    stopPolling();
    pollRef.current = setInterval(async () => {
      try {
        const { data } = await getApiClient().get<SessionStatus>(`/api/comparison/session/${sessionId}`);
        if (data.used && data.comparisonId) {
          stopPolling();
          setWaiting(false);
          router.push({ pathname: '/result/[id]', params: { id: data.comparisonId } } as never);
        } else if (new Date(data.expiresAt) < new Date()) {
          stopPolling();
          setWaiting(false);
          Toast.show({ type: 'info', text1: 'Session expired', text2: 'Generate a new QR code' });
          setSession(null);
        }
      } catch { /* ignore transient */ }
    }, 3000);
  };

  const createSession = async () => {
    setLoading(true);
    try {
      const { data } = await getApiClient().post<ComparisonSession>('/api/comparison/session');
      setSession(data);
      setWaiting(true);
      startPolling(data.id);
    } catch {
      Toast.show({ type: 'error', text1: 'Could not create session' });
    } finally {
      setLoading(false);
    }
  };

  const shareLink = async () => {
    if (!session) return;
    await Share.share({ message: `Let's see who we both know! Open Between Us: bus://compare/${session.token}` });
  };

  const reset = () => {
    stopPolling();
    setSession(null);
    setWaiting(false);
  };

  const handleBarcodeScan = ({ data }: { data: string }) => {
    if (scanned) return;
    // Accept both deep link format and raw token
    const match = data.match(/bus:\/\/compare\/([a-f0-9-]+)/i) ?? data.match(/^([a-f0-9-]{36})$/i);
    if (!match) {
      Toast.show({ type: 'error', text1: 'Invalid QR code', text2: 'This QR was not generated by Between Us' });
      return;
    }
    setScanned(true);
    router.push({ pathname: '/compare/[token]', params: { token: match[1] } } as never);
  };

  const switchMode = (next: Mode) => {
    if (next === 'show') stopPolling();
    setMode(next);
  };

  return (
    <View style={styles.container}>
      {/* Mode toggle */}
      <View style={styles.toggle}>
        <TouchableOpacity
          style={[styles.toggleBtn, mode === 'show' && styles.toggleActive]}
          onPress={() => switchMode('show')}
          activeOpacity={0.8}
        >
          <Text style={[styles.toggleText, mode === 'show' && styles.toggleTextActive]}>Show my code</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={[styles.toggleBtn, mode === 'scan' && styles.toggleActive]}
          onPress={() => switchMode('scan')}
          activeOpacity={0.8}
        >
          <Text style={[styles.toggleText, mode === 'scan' && styles.toggleTextActive]}>Scan a code</Text>
        </TouchableOpacity>
      </View>

      {mode === 'show' ? (
        // ── Show mode ──
        <View style={styles.content}>
          <Text style={styles.sub}>Generate a one-time QR code and show it to someone to find your mutual contacts.</Text>
          {!session ? (
            <TouchableOpacity style={styles.button} onPress={createSession} disabled={loading} activeOpacity={0.85}>
              {loading ? <ActivityIndicator color={Colors.white} /> : <Text style={styles.buttonText}>Generate QR Code</Text>}
            </TouchableOpacity>
          ) : (
            <View style={styles.qrCard}>
              <QRCode value={`bus://compare/${session.token}`} size={200} color={Colors.textPrimary} backgroundColor={Colors.surface} />
              <Text style={styles.tokenText}>Token: {session.token.slice(0, 8)}…</Text>
              {waiting ? (
                <View style={styles.waitRow}>
                  <ActivityIndicator color={Colors.primary} size="small" />
                  <Text style={styles.waitText}>Waiting for partner to scan…</Text>
                </View>
              ) : (
                <Text style={styles.expiry}>Expires {new Date(session.expiresAt).toLocaleTimeString()}</Text>
              )}
              <TouchableOpacity style={styles.shareButton} onPress={shareLink} activeOpacity={0.85}>
                <Text style={styles.shareText}>Share Link Instead</Text>
              </TouchableOpacity>
              <TouchableOpacity style={styles.resetButton} onPress={reset} activeOpacity={0.85}>
                <Text style={styles.resetText}>Generate New</Text>
              </TouchableOpacity>
            </View>
          )}
        </View>
      ) : (
        // ── Scan mode ──
        <View style={styles.content}>
          <Text style={styles.sub}>Point your camera at someone's Between Us QR code to start the comparison.</Text>
          {cameraGranted === null ? (
            <View style={styles.permCard}>
              <ActivityIndicator color={Colors.primary} />
              <Text style={[styles.permText, { marginTop: Spacing.md }]}>Checking camera permission…</Text>
            </View>
          ) : !cameraGranted ? (
            <View style={styles.permCard}>
              <Text style={styles.permText}>Camera access is needed to scan QR codes. Please grant the permission in Settings → Apps → Between Us → Permissions.</Text>
            </View>
          ) : (
            <View style={styles.cameraWrapper}>
              <CameraView
                style={styles.camera}
                facing="back"
                barcodeScannerSettings={{ barcodeTypes: ['qr'] }}
                onBarcodeScanned={scanned ? undefined : handleBarcodeScan}
              />
              <View style={styles.scanOverlay}>
                <View style={styles.scanCornerTL} />
                <View style={styles.scanCornerTR} />
                <View style={styles.scanCornerBL} />
                <View style={styles.scanCornerBR} />
              </View>
              {scanned && (
                <View style={styles.scannedBanner}>
                  <ActivityIndicator color={Colors.white} size="small" />
                  <Text style={styles.scannedText}>Joining comparison…</Text>
                </View>
              )}
            </View>
          )}
        </View>
      )}
    </View>
  );
}

const CORNER = 24;
const BORDER = 3;

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background, padding: Spacing.xxl },
  toggle: {
    flexDirection: 'row', backgroundColor: Colors.surface, borderRadius: Radii.full,
    padding: 4, marginTop: Spacing.xxxl, marginBottom: Spacing.xl,
    borderWidth: 1, borderColor: Colors.border,
  },
  toggleBtn: { flex: 1, paddingVertical: Spacing.sm, borderRadius: Radii.full, alignItems: 'center' },
  toggleActive: { backgroundColor: Colors.primary },
  toggleText: { fontSize: FontSize.body, fontFamily: Fonts.semiBold, color: Colors.textSecondary },
  toggleTextActive: { color: Colors.white },
  content: { flex: 1 },
  sub: { fontSize: FontSize.body, fontFamily: Fonts.regular, color: Colors.textSecondary, lineHeight: 22, marginBottom: Spacing.xl },
  button: { backgroundColor: Colors.primary, borderRadius: Radii.button, padding: Spacing.lg, alignItems: 'center' },
  buttonText: { fontSize: FontSize.body, fontFamily: Fonts.semiBold, color: Colors.white },
  qrCard: { backgroundColor: Colors.surface, borderRadius: Radii.card, padding: Spacing.xxl, alignItems: 'center', gap: Spacing.md, borderWidth: 1, borderColor: Colors.border },
  tokenText: { fontSize: FontSize.caption, fontFamily: Fonts.regular, color: Colors.textSecondary },
  waitRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  waitText: { fontSize: FontSize.body, fontFamily: Fonts.regular, color: Colors.primary },
  expiry: { fontSize: FontSize.small, fontFamily: Fonts.regular, color: Colors.warning },
  shareButton: { borderWidth: 1, borderColor: Colors.primary, borderRadius: Radii.button, paddingVertical: Spacing.md, paddingHorizontal: Spacing.xl },
  shareText: { fontSize: FontSize.body, fontFamily: Fonts.semiBold, color: Colors.primary },
  resetButton: { paddingVertical: Spacing.sm },
  resetText: { fontSize: FontSize.body, fontFamily: Fonts.regular, color: Colors.textSecondary },
  permCard: { backgroundColor: Colors.surface, borderRadius: Radii.card, padding: Spacing.xxl, gap: Spacing.lg, borderWidth: 1, borderColor: Colors.border },
  permText: { fontSize: FontSize.body, fontFamily: Fonts.regular, color: Colors.textSecondary, lineHeight: 22 },
  cameraWrapper: { flex: 1, borderRadius: Radii.card, overflow: 'hidden', position: 'relative', maxHeight: 400 },
  camera: { flex: 1 },
  scanOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, justifyContent: 'center', alignItems: 'center' },
  scanCornerTL: { position: 'absolute', top: '20%', left: '20%', width: CORNER, height: CORNER, borderTopWidth: BORDER, borderLeftWidth: BORDER, borderColor: Colors.primary },
  scanCornerTR: { position: 'absolute', top: '20%', right: '20%', width: CORNER, height: CORNER, borderTopWidth: BORDER, borderRightWidth: BORDER, borderColor: Colors.primary },
  scanCornerBL: { position: 'absolute', bottom: '20%', left: '20%', width: CORNER, height: CORNER, borderBottomWidth: BORDER, borderLeftWidth: BORDER, borderColor: Colors.primary },
  scanCornerBR: { position: 'absolute', bottom: '20%', right: '20%', width: CORNER, height: CORNER, borderBottomWidth: BORDER, borderRightWidth: BORDER, borderColor: Colors.primary },
  scannedBanner: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: Colors.primary + 'CC', flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: Spacing.sm, padding: Spacing.md },
  scannedText: { fontSize: FontSize.body, fontFamily: Fonts.semiBold, color: Colors.white },
});
